### ISSUE TITLE
user.bookmarks: cannot use a bytes pattern on a string-like object

### ISSUE THREAD

**Issue by enjoymoreradio** [kannibalox/PTPAPI#19]
Tried to request my bookmarks and was met with this error. Issue appears to be that bookmarks passes the string-type req.text to snarf_cover_view_data(), rather than the bytes-type req.content.

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/enjoymoreradio/.local/lib/python3.10/site-packages/ptpapi/user.py", line 32, in bookmarks
    for movie in snarf_cover_view_data(req.text):
  File "/home/enjoymoreradio/.local/lib/python3.10/site-packages/ptpapi/util.py", line 120, in snarf_cover_view_data
    for json_data in re.finditer(key + rb"\s*=\s*({.*});", text, flags=re.DOTALL):
  File "/usr/lib/python3.10/re.py", line 247, in finditer
    return _compile(pattern, flags).finditer(string)
TypeError: cannot use a bytes pattern on a string-like object

**Comment by kannibalox** [comment]
Thanks for the report!
