### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 73: ordinal not in range(128)

### ISSUE THREAD

**Issue by mrjack711** [kannibalox/PTPAPI#3]
Similar issue to one reported previously.

Traceback (most recent call last):
  File "/usr/local/bin/ptp-reseed", line 11, in <module>
    load_entry_point('PTPAPI==0.5', 'console_scripts', 'ptp-reseed')()
  File "/usr/local/lib/python2.7/dist-packages/ptpapi/scripts/ptp_reseed.py", line 300, in main
    logger.info(u'Starting reseed attempt on file {0}'.format(filename))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 73: ordinal not in range(128)

I think it failed on:
"Hungarian Rhapsody Queen Live in Budapest ’86[BDRemux.1080p].mkv"

**Comment by mrjack711** [comment]
Also had a failure on a file with ® in its name.
